import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>

        <nav
          style={{
            backgroundColor: "teal",
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            gap: "10px",
            height: "100px",
          }}
        >
          <Link href="/">
            <button
              style={{ height: "50px", width: "100px",border:"none", borderRadius: "7px" }}
            >
              Home
            </button>
          </Link>

          <Link href="/posts">
            <button
              style={{ height: "50px", width: "100px",border:"none", borderRadius: "7px" }}
            >
              Posts
            </button>
          </Link>

          <Link href="/articles">
            <button
              style={{ height: "50px", width: "100px",border:"none", borderRadius: "7px" }}
            >
              Articles
            </button>
          </Link>
        </nav>

        {children}

        
      </body>
    </html>
  );
}
